### PR TITLE
Enforce maximum upload size

### LINKED ISSUE #299: Report an error when objects become too big to upload
We can't upload an object of size larger than `part_size * 10000` to S3. Right now that failure only happens asynchronously when the CRT tries to actually upload the 10001th part, so the application has a hard time finding out about it. We should track the object size on our side and fail writes with `libc::EFBIG` when an object gets too big.

### PR DESCRIPTION
**Pull request by jamesbornholt**
This turned out to be a lot of refactoring to expose the client's part size and allow our FUSE tests to choose a part size. So it might be easier to read the three commits individually.

## Description of change

Uploads can fail if they require more than 10,000 parts. Right now we
only find out about that failure asynchronously when the CRT actually
constructs the 10,0001th part. This is bad because unlike other upload
errors, this one is a deterministic failure that we should be able to
report up front.

One trick here is that the kernel appears to retry failed writes from
page cache when returning EFBIG, so we need to remember the reason the
write failed.

Relevant issues: Fixes #299

## Does this change impact existing behavior?

Yes, uploads will fail earlier than they did before, and with a different error code.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and I agree to the terms of the [Developer Certificate of Origin (DCO)](https://developercertificate.org/).

### CODE REVIEW

File: mountpoint-s3-client/src/s3_crt_client.rs [hunk 1]
```diff
@@ -67,14 +67,75 @@ macro_rules! event {
...
+    user_agent_prefix: Option<String>,
+    request_payer: Option<String>,
+}
+
+impl Default for S3ClientConfig {
+    fn default() -> Self {
+        Self {
+            auth_config: Default::default(),
+            throughput_target_gbps: 10.0,
+            part_size: 8 * 1024 * 1024,
```
Comment (passaro) [inline mountpoint-s3-client/src/s3_crt_client.rs:85]: Default values are duplicated here and in mountpoint main. Not sure what to do about it, except maybe a comment here or there.

File: mountpoint-s3-client/src/s3_crt_client.rs [hunk 2]
```diff
@@ -662,6 +718,10 @@ impl ObjectClient for S3CrtClient {
     type PutObjectRequest = S3PutObjectRequest;
     type ClientError = S3RequestError;
 
+    fn part_size(&self) -> Option<usize> {
+        Some(self.inner.part_size)
```
Comment (passaro) [inline mountpoint-s3-client/src/s3_crt_client.rs:722]: Is this the actual part size or just what we set in ClientConfig? AFAIK the CRT will do some clamping.

File: mountpoint-s3/src/fs.rs [hunk 3]
```diff
@@ -76,13 +77,14 @@ impl<Client: ObjectClient> UploadState<Client> {
             Err(e) => {
                 error!("write failed: {e}");
                 match e {
-                    UploadWriteError::PutRequestFailed(_) => {
+                    UploadWriteError::PutRequestFailed(_) | UploadWriteError::ObjectTooBig { .. } => {
```
Comment (passaro) [inline mountpoint-s3/src/fs.rs:80]: Arguably, we could treat `ObjectTooBig` like `OutOfOrderWrite`: do not set the upload to `Failed` and allow for retries with a size that fits and/or subsequent fsync/release.
Is this a conscious choice not to do that?

I may also not fully understand the issue with kernel retries: wouldn't they also fail just with the size check in `UploadRequest::write`?

Comment (passaro) [reply mountpoint-s3/src/fs.rs:80]: But I do like recording the error in `Failed` in general!

**Review by passaro — COMMENTED** [review]
Just a few questions, mostly non-blocking. The only one that concerns me a bit is whether we are getting the actual part size from the CRT.

File: mountpoint-s3-client/src/s3_crt_client.rs (hunk 2 above)
Comment (jamesbornholt) [reply mountpoint-s3-client/src/s3_crt_client.rs:734]: Yeah, the CRT doesn't let us interrogate the actual part size. But right now the only clamping it does is to the 5GiB part size limit, so I added the same clamping to our constructor.

File: mountpoint-s3/src/fs.rs (hunk 3 above)
Comment (jamesbornholt) [reply mountpoint-s3/src/fs.rs:80]: It was a conscious choice because I'm worried about uploading truncated objects. On reflection I think we should do the same thing for out-of-order writes -- we'd rather fail loudly in case applications don't actually check the results of `write`. Let's do that in a separate change.

> I may also not fully understand the issue with kernel retries: wouldn't they also fail just with the size check in UploadRequest::write?

No, because `UploadRequest::write` checks whether the upload has failed before calling `upload.write`, which is where the size check is.

Comment (passaro) [reply mountpoint-s3/src/fs.rs:80]: > No, because `UploadRequest::write` checks whether the upload has failed before calling `upload.write`, which is where the size check is.

Sure, but it wouldn't if we treated it like `OutOfOrderWrite`. Anyway, happy to change the behavior of the latter.

**Review by passaro — APPROVED** [review]
