### PR TITLE
Present flexible retrieval objects with 000 permissions

### LINKED ISSUE #152: Decide how to handle Glacier Flexible Retrieval & Glacier Deep Archive objects
Right now, trying to read Glacier Flexible Retrieval or Glacier Deep Archive objects fails with EIO.

```
[ec2-user@ip-172-31-3-74 ~]$ aws s3api head-object --bucket bornholt-test-bucket --key test2GiB-GIR
{
    "AcceptRanges": "bytes",
    "ContentType": "binary/octet-stream",
    "LastModified": "Wed, 15 Mar 2023 15:59:10 GMT",
    "ContentLength": 2147483648,
    "ETag": "\"f7554c62cdd5d27e20d1a9badb5649a6-256\"",
    "StorageClass": "GLACIER_IR",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
[ec2-user@ip-172-31-3-74 ~]$ stat mnt/test2GiB-GIR
  File: ‘mnt/test2GiB-GIR’
  Size: 2147483648      Blocks: 4194304    IO Block: 4096   regular file
Device: 2ah/42d Inode: 28          Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/ec2-user)   Gid: ( 1000/ec2-user)
Access: 2023-03-15 15:59:10.000000000 +0000
Modify: 2023-03-15 15:59:10.000000000 +0000
Change: 2023-03-15 15:59:10.000000000 +0000
 Birth: -
[ec2-user@ip-172-31-3-74 ~]$ md5sum mnt/test2GiB-GIR
0a4b09e620dd66537b62cf2b8cdd5143  mnt/test2GiB-GIR

[ec2-user@ip-172-31-3-74 ~]$ aws s3api head-object --bucket bornholt-test-bucket --key test2GiB-GFR
{
    "AcceptRanges": "bytes",
    "ContentType": "binary/octet-stream",
    "LastModified": "Wed, 15 Mar 2023 15:58:17 GMT",
    "ContentLength": 2147483648,
    "ETag": "\"f7554c62cdd5d27e20d1a9badb5649a6-256\"",
    "StorageClass": "GLACIER",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
[ec2-user@ip-172-31-3-74 ~]$ stat mnt/test2GiB-GFR
  File: ‘mnt/test2GiB-GFR’
  Size: 2147483648      Blocks: 4194304    IO Block: 4096   regular file
Device: 2ah/42d Inode: 27          Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/ec2-user)   Gid: ( 1000/ec2-user)
Access: 2023-03-15 15:58:17.000000000 +0000
Modify: 2023-03-15 15:58:17.000000000 +0000
Change: 2023-03-15 15:58:17.000000000 +0000
 Birth: -
[ec2-user@ip-172-31-3-74 ~]$ md5sum mnt/test2GiB-GFR
md5sum: mnt/test2GiB-GFR: Input/output error

[ec2-user@ip-172-31-3-74 ~]$ aws s3api head-object --bucket bornholt-test-bucket --key test2GiB-GDA
{
    "AcceptRanges": "bytes",
    "ContentType": "binary/octet-stream",
    "LastModified": "Wed, 15 Mar 2023 16:00:01 GMT",
    "ContentLength": 2147483648,
    "ETag": "\"f7554c62cdd5d27e20d1a9badb5649a6-256\"",
    "StorageClass": "DEEP_ARCHIVE",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
[ec2-user@ip-172-31-3-74 ~]$ stat mnt/test2GiB-GDA
  File: ‘mnt/test2GiB-GDA’
  Size: 2147483648      Blocks: 4194304    IO Block: 4096   regular file
Device: 2ah/42d Inode: 26          Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/ec2-user)   Gid: ( 1000/ec2-user)
Access: 2023-03-15 16:00:01.000000000 +0000
Modify: 2023-03-15 16:00:01.000000000 +0000
Change: 2023-03-15 16:00:01.000000000 +0000
 Birth: -
[ec2-user@ip-172-31-3-74 ~]$ md5sum mnt/test2GiB-GDA
md5sum: mnt/test2GiB-GDA: Input/output error
```

Three things to figure out about this:
1. Should GFR/GDA objects show up in the file system at all, if they're inaccessible?
2. Is EIO the right way to fail reads for these?
3. We need to document whatever our intended behavior is here.

### PR DESCRIPTION
**Pull request by jamesbornholt**
## Description of change

Objects in the Glacier Flexible Retrieval and Glacier Deep Archive
storage classes (and their corresponding Intelligent Tiering tiers) are
not readable with GetObject without first triggering a restoration. We
don't offer the ability to do that (and it likely wouldn't make sense
for us given the latency), but these objects will still appear in the
file tree, so we give them 000 permissions and EACCES failures to make
clear they're not accessible.

It would be nice to make this work for objects that have already been
restored, which still carry the GLACIER/DEEP_ARCHIVE storage class but
also return their restore state with HeadObject. But ListObjectsV2 gives
us no way to find that out. We could probably make this work since we
know we always send a HeadObject on `open`, but it was more work than I
wanted to do right now, and this at least prevents customers getting EIO
errors on these objects.

Relevant issues: fixes #152.

## Does this change impact existing behavior?

Yes, this changes the permissions for Glacier Flexible Retrieval and Glacier Deep Archive objects.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and I agree to the terms of the [Developer Certificate of Origin (DCO)](https://developercertificate.org/).

### CODE REVIEW

File: mountpoint-s3/src/fs.rs [hunk 1]
```diff
@@ -366,7 +391,13 @@ where
         // hard links, so we just assume one link for files (itself) and two links for directories
         // (itself + the "." link).
         let (perm, nlink) = match lookup.inode.kind() {
-            InodeKind::File => (self.config.file_mode, 1),
+            InodeKind::File => {
+                if is_flexible_retrieval_storage_class(lookup) {
+                    (0o000, 1)
```
Comment (passaro) [inline mountpoint-s3/src/fs.rs:396]: If we ever allow over-writing, will this be a breaking change?

Should we just mask `config.file_mode` to disallow rx?

File: mountpoint-s3/src/inode.rs [hunk 2]
```diff
@@ -1214,6 +1214,8 @@ pub struct InodeStat {
     pub atime: OffsetDateTime,
     /// Etag for the file (object)
     pub etag: Option<String>,
+    /// Storage class for the file (object), if known
+    pub storage_class: Option<String>,
```
Comment (passaro) [inline mountpoint-s3/src/inode.rs:1218]: I worry the extra string here could be quite wasteful (and redundant!). Maybe we could just store the resulting permissions here instead of the storage class.

Comment (jamesbornholt) [reply mountpoint-s3/src/inode.rs]: I didn't want to inline the permissions here (our inode stats otherwise don't know about POSIX permissions). But this was a great chance to use my new favorite-named crate, [lasso](https://crates.io/crates/lasso), to intern the storage class names!

**Review by passaro — APPROVED** [review]

File: mountpoint-s3/src/inode.rs (hunk 2 above)
Comment (passaro) [reply mountpoint-s3/src/inode.rs]: Cool. Is that a Texan thing?
